# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\AVOR\Desktop\CPET 8\QtProjects\MAIN.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Main(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1179, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 1181, 61))
        self.label.setStyleSheet("font: 75 12pt \"Rockwell\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-10, 0, 1191, 691))
        self.label_4.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 1181, 81))
        self.label_8.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 181, 611))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.BACKUP = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.BACKUP.setGeometry(QtCore.QRect(0, 410, 181, 51))
        self.BACKUP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BACKUP.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 20pt \"Rockwell\";")
        self.BACKUP.setObjectName("BACKUP")
        self.EXAM = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.EXAM.setGeometry(QtCore.QRect(0, 140, 181, 51))
        self.EXAM.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EXAM.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 20pt \"Rockwell\";")
        self.EXAM.setObjectName("EXAM")
        self.REPORT = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.REPORT.setGeometry(QtCore.QRect(0, 540, 181, 51))
        self.REPORT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.REPORT.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 20pt \"Rockwell\";")
        self.REPORT.setObjectName("REPORT")
        self.RESULTS = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.RESULTS.setGeometry(QtCore.QRect(0, 280, 181, 51))
        self.RESULTS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RESULTS.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 20pt \"Rockwell\";")
        self.RESULTS.setObjectName("RESULTS")
        self.HOME = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.HOME.setGeometry(QtCore.QRect(50, 20, 101, 41))
        self.HOME.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.HOME.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Rockwell\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\AVOR\\Desktop\\CPET 8\\QtProjects\\83684799-premium-home-icon-or-logo-in-line-style-high-quality-sign-and-symbol-on-a-white-background-vector-ou.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HOME.setIcon(icon)
        self.HOME.setObjectName("HOME")
        self.LOGOUT = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.LOGOUT.setGeometry(QtCore.QRect(1010, 20, 131, 41))
        self.LOGOUT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LOGOUT.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Rockwell\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\AVOR\\Desktop\\CPET 8\\QtProjects\\istockphoto-827252562-612x612.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LOGOUT.setIcon(icon1)
        self.LOGOUT.setObjectName("LOGOUT")
        self.BackupFrame = QtWidgets.QFrame(self.centralwidget)
        self.BackupFrame.setGeometry(QtCore.QRect(180, 80, 1001, 611))
        self.BackupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BackupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BackupFrame.setObjectName("BackupFrame")
        self.label_27 = QtWidgets.QLabel(self.BackupFrame)
        self.label_27.setGeometry(QtCore.QRect(60, 0, 881, 31))
        self.label_27.setStyleSheet("font: 75 14pt \"Rockwell\";")
        self.label_27.setObjectName("label_27")
        self.SaveData = QtWidgets.QCommandLinkButton(self.BackupFrame)
        self.SaveData.setGeometry(QtCore.QRect(480, 530, 421, 51))
        self.SaveData.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SaveData.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);\n"
"font: 75 20pt \"Rockwell\";")
        icon = QtGui.QIcon.fromTheme("none")
        self.SaveData.setIcon(icon)
        self.SaveData.setObjectName("SaveData")
        self.BackupTable = QtWidgets.QTableWidget(self.BackupFrame)
        self.BackupTable.setGeometry(QtCore.QRect(100, 30, 801, 501))
        self.BackupTable.setStyleSheet("font: 75 10pt \"Rockwell\";")
        self.BackupTable.setObjectName("BackupTable")
        self.BackupTable.setColumnCount(8)
        self.BackupTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.BackupTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BackupTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BackupTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BackupTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BackupTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BackupTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BackupTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BackupTable.setHorizontalHeaderItem(7, item)
        self.SaveData_2 = QtWidgets.QCommandLinkButton(self.BackupFrame)
        self.SaveData_2.setGeometry(QtCore.QRect(100, 530, 381, 51))
        self.SaveData_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SaveData_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);\n"
"font: 75 20pt \"Rockwell\";")
        icon = QtGui.QIcon.fromTheme("none")
        self.SaveData_2.setIcon(icon)
        self.SaveData_2.setObjectName("SaveData_2")
        self.label_42 = QtWidgets.QLabel(self.BackupFrame)
        self.label_42.setGeometry(QtCore.QRect(100, 530, 801, 51))
        self.label_42.setStyleSheet("font: 75 14pt \"Rockwell\";\n"
"background-color: rgb(0, 0, 0);")
        self.label_42.setObjectName("label_42")
        self.label_27.raise_()
        self.BackupTable.raise_()
        self.label_42.raise_()
        self.SaveData_2.raise_()
        self.SaveData.raise_()
        self.HomeAdmin = QtWidgets.QFrame(self.centralwidget)
        self.HomeAdmin.setGeometry(QtCore.QRect(170, 80, 1011, 611))
        self.HomeAdmin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HomeAdmin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HomeAdmin.setObjectName("HomeAdmin")
        self.label_12 = QtWidgets.QLabel(self.HomeAdmin)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 1001, 61))
        self.label_12.setStyleSheet("font: 75 25pt \"Rockwell\";\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.HomeAdmin)
        self.label_14.setGeometry(QtCore.QRect(40, 20, 301, 311))
        self.label_14.setStyleSheet("image: url(:/AdminProf/pic.png);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.HomeAdmin)
        self.label_15.setGeometry(QtCore.QRect(10, 180, 1001, 31))
        self.label_15.setStyleSheet("font: 75 12pt \"Rockwell\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.HomeAdmin)
        self.label_16.setGeometry(QtCore.QRect(760, 540, 61, 16))
        self.label_16.setStyleSheet("font: 75 12pt \"Rockwell\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.HomeAdmin)
        self.label_17.setGeometry(QtCore.QRect(10, 270, 1001, 251))
        self.label_17.setStyleSheet("font: 75 12pt \"Rockwell\";")
        self.label_17.setObjectName("label_17")
        self.DATE_2 = QtWidgets.QLabel(self.HomeAdmin)
        self.DATE_2.setGeometry(QtCore.QRect(820, 540, 91, 16))
        self.DATE_2.setText("")
        self.DATE_2.setObjectName("DATE_2")
        self.AdminResults = QtWidgets.QFrame(self.centralwidget)
        self.AdminResults.setGeometry(QtCore.QRect(180, 80, 1001, 611))
        self.AdminResults.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AdminResults.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AdminResults.setObjectName("AdminResults")
        self.label_18 = QtWidgets.QLabel(self.AdminResults)
        self.label_18.setGeometry(QtCore.QRect(30, 10, 701, 51))
        self.label_18.setStyleSheet("font: 75 14pt \"Rockwell\";")
        self.label_18.setObjectName("label_18")
        self.SEARCH = QtWidgets.QCommandLinkButton(self.AdminResults)
        self.SEARCH.setGeometry(QtCore.QRect(750, 260, 221, 41))
        self.SEARCH.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SEARCH.setStyleSheet("font: 75 16pt \"Rockwell\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.SEARCH.setObjectName("SEARCH")
        self.lineEdit = QtWidgets.QLineEdit(self.AdminResults)
        self.lineEdit.setGeometry(QtCore.QRect(750, 230, 221, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_19 = QtWidgets.QLabel(self.AdminResults)
        self.label_19.setGeometry(QtCore.QRect(690, 10, 311, 211))
        self.label_19.setStyleSheet("image: url(:/AdminProf/pic.png);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.AdminResults)
        self.label_20.setGeometry(QtCore.QRect(750, 330, 221, 31))
        self.label_20.setStyleSheet("font: 75 14pt \"Rockwell\";")
        self.label_20.setObjectName("label_20")
        self.PASS = QtWidgets.QCommandLinkButton(self.AdminResults)
        self.PASS.setGeometry(QtCore.QRect(750, 360, 221, 41))
        self.PASS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PASS.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);\n"
"font: 75 14pt \"Rockwell\";")
        self.PASS.setObjectName("PASS")
        self.FAIL = QtWidgets.QCommandLinkButton(self.AdminResults)
        self.FAIL.setGeometry(QtCore.QRect(750, 400, 221, 41))
        self.FAIL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FAIL.setStyleSheet("font: 75 14pt \"Rockwell\";\n"
"background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.FAIL.setObjectName("FAIL")
        self.label_21 = QtWidgets.QLabel(self.AdminResults)
        self.label_21.setGeometry(QtCore.QRect(750, 260, 221, 41))
        self.label_21.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.AdminResults)
        self.label_22.setGeometry(QtCore.QRect(750, 360, 221, 171))
        self.label_22.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.HIGHEST = QtWidgets.QCommandLinkButton(self.AdminResults)
        self.HIGHEST.setGeometry(QtCore.QRect(750, 440, 221, 41))
        self.HIGHEST.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.HIGHEST.setStyleSheet("font: 75 14pt \"Rockwell\";\n"
"background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.HIGHEST.setObjectName("HIGHEST")
        self.LOWEST = QtWidgets.QCommandLinkButton(self.AdminResults)
        self.LOWEST.setGeometry(QtCore.QRect(750, 480, 221, 41))
        self.LOWEST.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LOWEST.setStyleSheet("font: 75 14pt \"Rockwell\";\n"
"background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.LOWEST.setObjectName("LOWEST")
        self.ResultsTable = QtWidgets.QTableWidget(self.AdminResults)
        self.ResultsTable.setGeometry(QtCore.QRect(30, 50, 701, 531))
        self.ResultsTable.setStyleSheet("font: 75 10pt \"Rockwell\";")
        self.ResultsTable.setObjectName("ResultsTable")
        self.ResultsTable.setColumnCount(8)
        self.ResultsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ResultsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultsTable.setHorizontalHeaderItem(7, item)
        self.label_18.raise_()
        self.lineEdit.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.SEARCH.raise_()
        self.label_22.raise_()
        self.FAIL.raise_()
        self.PASS.raise_()
        self.HIGHEST.raise_()
        self.LOWEST.raise_()
        self.ResultsTable.raise_()
        self.ReportFrame = QtWidgets.QFrame(self.centralwidget)
        self.ReportFrame.setGeometry(QtCore.QRect(180, 80, 1001, 611))
        self.ReportFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ReportFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ReportFrame.setObjectName("ReportFrame")
        self.label_30 = QtWidgets.QLabel(self.ReportFrame)
        self.label_30.setGeometry(QtCore.QRect(0, 40, 1001, 391))
        self.label_30.setStyleSheet("image: url(:/AdminProf/pic.png);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.SHOWEXCEL = QtWidgets.QCommandLinkButton(self.ReportFrame)
        self.SHOWEXCEL.setGeometry(QtCore.QRect(60, 430, 501, 81))
        self.SHOWEXCEL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SHOWEXCEL.setStyleSheet("font: 75 40pt \"Rockwell\";\n"
"background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.SHOWEXCEL.setObjectName("SHOWEXCEL")
        self.PRINT = QtWidgets.QCommandLinkButton(self.ReportFrame)
        self.PRINT.setGeometry(QtCore.QRect(570, 430, 361, 81))
        self.PRINT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PRINT.setStyleSheet("font: 75 40pt \"Rockwell\";\n"
"background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.PRINT.setObjectName("PRINT")
        self.label_31 = QtWidgets.QLabel(self.ReportFrame)
        self.label_31.setGeometry(QtCore.QRect(60, 430, 501, 81))
        self.label_31.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.ReportFrame)
        self.label_32.setGeometry(QtCore.QRect(570, 430, 361, 81))
        self.label_32.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_30.raise_()
        self.label_31.raise_()
        self.SHOWEXCEL.raise_()
        self.label_32.raise_()
        self.PRINT.raise_()
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(0, 220, 181, 31))
        self.label_33.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(0, 360, 181, 31))
        self.label_34.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(0, 480, 181, 31))
        self.label_35.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(0, 120, 181, 91))
        self.label_37.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(0, 260, 181, 91))
        self.label_38.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(0, 390, 181, 91))
        self.label_39.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(0, 520, 181, 91))
        self.label_40.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.AdminAddExam = QtWidgets.QFrame(self.centralwidget)
        self.AdminAddExam.setGeometry(QtCore.QRect(190, 60, 1001, 611))
        self.AdminAddExam.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AdminAddExam.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AdminAddExam.setObjectName("AdminAddExam")
        self.ADDEXAM = QtWidgets.QCommandLinkButton(self.AdminAddExam)
        self.ADDEXAM.setGeometry(QtCore.QRect(330, 230, 361, 91))
        self.ADDEXAM.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ADDEXAM.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 48pt \"Rockwell\";")
        icon = QtGui.QIcon.fromTheme("none")
        self.ADDEXAM.setIcon(icon)
        self.ADDEXAM.setObjectName("ADDEXAM")
        self.label_36 = QtWidgets.QLabel(self.AdminAddExam)
        self.label_36.setGeometry(QtCore.QRect(0, 230, 1001, 91))
        self.label_36.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_41 = QtWidgets.QLabel(self.AdminAddExam)
        self.label_41.setGeometry(QtCore.QRect(330, 10, 361, 221))
        self.label_41.setStyleSheet("image: url(:/AdminProf/pic.png);")
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.label_43 = QtWidgets.QLabel(self.AdminAddExam)
        self.label_43.setGeometry(QtCore.QRect(0, 330, 1001, 91))
        self.label_43.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.VIEWEXAMINEES = QtWidgets.QCommandLinkButton(self.AdminAddExam)
        self.VIEWEXAMINEES.setGeometry(QtCore.QRect(170, 330, 691, 91))
        self.VIEWEXAMINEES.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VIEWEXAMINEES.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 48pt \"Rockwell\";")
        icon = QtGui.QIcon.fromTheme("none")
        self.VIEWEXAMINEES.setIcon(icon)
        self.VIEWEXAMINEES.setObjectName("VIEWEXAMINEES")
        self.NAMES = QtWidgets.QLineEdit(self.AdminAddExam)
        self.NAMES.setGeometry(QtCore.QRect(140, 450, 121, 31))
        self.NAMES.setStyleSheet("font: 14pt \"Rockwell\";")
        self.NAMES.setText("")
        self.NAMES.setObjectName("NAMES")
        self.label_3 = QtWidgets.QLabel(self.AdminAddExam)
        self.label_3.setGeometry(QtCore.QRect(20, 450, 111, 31))
        self.label_3.setStyleSheet("font: 14pt \"Rockwell\";")
        self.label_3.setObjectName("label_3")
        self.SCORE = QtWidgets.QLineEdit(self.AdminAddExam)
        self.SCORE.setGeometry(QtCore.QRect(410, 450, 51, 31))
        self.SCORE.setStyleSheet("font: 18pt \"Rockwell\";")
        self.SCORE.setText("")
        self.SCORE.setObjectName("SCORE")
        self.label_44 = QtWidgets.QLabel(self.AdminAddExam)
        self.label_44.setGeometry(QtCore.QRect(60, 540, 401, 41))
        self.label_44.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.CONFIRM = QtWidgets.QCommandLinkButton(self.AdminAddExam)
        self.CONFIRM.setGeometry(QtCore.QRect(60, 540, 401, 41))
        self.CONFIRM.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CONFIRM.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"font: 15pt \"Rockwell\";\n"
"color: rgb(255, 255, 255);\n"
"")
        icon = QtGui.QIcon.fromTheme("none")
        self.CONFIRM.setIcon(icon)
        self.CONFIRM.setObjectName("CONFIRM")
        self.label_5 = QtWidgets.QLabel(self.AdminAddExam)
        self.label_5.setGeometry(QtCore.QRect(280, 450, 131, 31))
        self.label_5.setStyleSheet("font: 14pt \"Rockwell\";")
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.AdminAddExam)
        self.label_11.setGeometry(QtCore.QRect(490, 480, 491, 31))
        self.label_11.setStyleSheet("font: 14pt \"Rockwell\";")
        self.label_11.setObjectName("label_11")
        self.label_49 = QtWidgets.QLabel(self.AdminAddExam)
        self.label_49.setGeometry(QtCore.QRect(520, 520, 401, 41))
        self.label_49.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.VIEWALL = QtWidgets.QCommandLinkButton(self.AdminAddExam)
        self.VIEWALL.setGeometry(QtCore.QRect(520, 520, 401, 41))
        self.VIEWALL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VIEWALL.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"font: 15pt \"Rockwell\";\n"
"color: rgb(255, 255, 255);\n"
"")
        icon = QtGui.QIcon.fromTheme("none")
        self.VIEWALL.setIcon(icon)
        self.VIEWALL.setObjectName("VIEWALL")
        self.PASS_2 = QtWidgets.QRadioButton(self.AdminAddExam)
        self.PASS_2.setGeometry(QtCore.QRect(280, 500, 82, 17))
        self.PASS_2.setStyleSheet("font: 14pt \"Rockwell\";")
        self.PASS_2.setObjectName("PASS_2")
        self.FAIL_2 = QtWidgets.QRadioButton(self.AdminAddExam)
        self.FAIL_2.setGeometry(QtCore.QRect(370, 500, 82, 17))
        self.FAIL_2.setStyleSheet("font: 14pt \"Rockwell\";")
        self.FAIL_2.setObjectName("FAIL_2")
        self.label_6 = QtWidgets.QLabel(self.AdminAddExam)
        self.label_6.setGeometry(QtCore.QRect(20, 490, 111, 31))
        self.label_6.setStyleSheet("font: 14pt \"Rockwell\";")
        self.label_6.setObjectName("label_6")
        self.FIRSTNAME = QtWidgets.QLineEdit(self.AdminAddExam)
        self.FIRSTNAME.setGeometry(QtCore.QRect(140, 490, 121, 31))
        self.FIRSTNAME.setStyleSheet("font: 14pt \"Rockwell\";")
        self.FIRSTNAME.setText("")
        self.FIRSTNAME.setObjectName("FIRSTNAME")
        self.label_36.raise_()
        self.ADDEXAM.raise_()
        self.label_41.raise_()
        self.label_43.raise_()
        self.VIEWEXAMINEES.raise_()
        self.NAMES.raise_()
        self.label_3.raise_()
        self.SCORE.raise_()
        self.label_44.raise_()
        self.CONFIRM.raise_()
        self.label_5.raise_()
        self.label_11.raise_()
        self.label_49.raise_()
        self.VIEWALL.raise_()
        self.PASS_2.raise_()
        self.FAIL_2.raise_()
        self.label_6.raise_()
        self.FIRSTNAME.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.HOME.raise_()
        self.LOGOUT.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_37.raise_()
        self.EXAM.raise_()
        self.label_38.raise_()
        self.RESULTS.raise_()
        self.label_39.raise_()
        self.BACKUP.raise_()
        self.label_40.raise_()
        self.REPORT.raise_()
        self.AdminAddExam.raise_()
        self.AdminResults.raise_()
        self.BackupFrame.raise_()
        self.HomeAdmin.raise_()
        self.ReportFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AdminMain"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">I.E DEPARTMENT</span></p></body></html>"))
        self.BACKUP.setText(_translate("MainWindow", "BACKUP"))
        self.EXAM.setText(_translate("MainWindow", "EXAM"))
        self.REPORT.setText(_translate("MainWindow", "REPORT"))
        self.RESULTS.setText(_translate("MainWindow", "RESULTS"))
        self.HOME.setText(_translate("MainWindow", "HOME"))
        self.LOGOUT.setText(_translate("MainWindow", "LOG OUT"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Students Data</p></body></html>"))
        self.SaveData.setText(_translate("MainWindow", "                SAVE ALL DATA"))
        item = self.BackupTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lastname"))
        item = self.BackupTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Firstname"))
        item = self.BackupTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Middlename"))
        item = self.BackupTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Shift"))
        item = self.BackupTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Username"))
        item = self.BackupTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Passwd"))
        item = self.BackupTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        item = self.BackupTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Scores"))
        self.SaveData_2.setText(_translate("MainWindow", "                   DELETE"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">WELCOME</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">SYSTEM ADMINISTRATOR</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "DATE :"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">\'Welcome admin, here you can now access the system</span></p><p align=\"center\"><span style=\" font-size:18pt;\">by showing results of the examination and you can now</span></p><p align=\"center\"><span style=\" font-size:18pt;\">backup, report, and print the results. Have a nice day.\'</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">NAMES / RESULTS:</p></body></html>"))
        self.SEARCH.setText(_translate("MainWindow", "SEARCH"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Name"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">SORT :</span></p></body></html>"))
        self.PASS.setText(_translate("MainWindow", "PASS"))
        self.FAIL.setText(_translate("MainWindow", "FAIL"))
        self.HIGHEST.setText(_translate("MainWindow", "HIGHEST"))
        self.LOWEST.setText(_translate("MainWindow", "LOWEST"))
        item = self.ResultsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lastname"))
        item = self.ResultsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Firstname"))
        item = self.ResultsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Middlename"))
        item = self.ResultsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Shift"))
        item = self.ResultsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Username"))
        item = self.ResultsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Passwd"))
        item = self.ResultsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        item = self.ResultsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Score"))
        self.SHOWEXCEL.setText(_translate("MainWindow", "SHOW IN EXCEL"))
        self.PRINT.setText(_translate("MainWindow", "PRINT"))
        self.ADDEXAM.setText(_translate("MainWindow", "ADD EXAM"))
        self.VIEWEXAMINEES.setText(_translate("MainWindow", "VIEW ALL EXAMINEES"))
        self.label_3.setText(_translate("MainWindow", "LASTNAME:"))
        self.CONFIRM.setText(_translate("MainWindow", "                            CONFIRM"))
        self.label_5.setText(_translate("MainWindow", "SET A SCORE:"))
        self.label_11.setText(_translate("MainWindow", "LIST OF STUDENTS SET THERE EXAMINATION DATES:"))
        self.VIEWALL.setText(_translate("MainWindow", "                            VIEW ALL"))
        self.PASS_2.setText(_translate("MainWindow", "PASS"))
        self.FAIL_2.setText(_translate("MainWindow", "FAIL"))
        self.label_6.setText(_translate("MainWindow", "FIRSTNAME:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Main()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
